import React, { useState, useRef } from 'react';
import html2canvas from 'html2canvas';

const PostcardTemplate = ({ song, ticket, selectedCoverImg, customMessage, lyrics }) => {
  return (
    // ★ 統一風格：明信片加上厚黑邊框與陰影
    <div className="w-[900px] h-[500px] bg-[#FDFBF7] flex flex-row overflow-hidden border-[4px] border-gray-800 shadow-[8px_8px_0_rgba(0,0,0,0.8)]">
      <div className="w-[350px] flex flex-col border-r-[4px] border-dashed border-gray-800 relative bg-white">
        
        <div className="w-full h-[260px] bg-gray-200 relative overflow-hidden border-b-[4px] border-red-600 p-3 pb-0">
          {selectedCoverImg ? (
            <img src={selectedCoverImg} className="w-full h-full object-cover rounded-t-lg shadow-inner border-[3px] border-gray-800 border-b-0" alt="Cover" />
          ) : (
            <div className="w-full h-full flex items-center justify-center text-gray-400 font-bold tracking-widest border-[3px] border-gray-800 border-b-0 rounded-t-lg">無圖片</div>
          )}
        </div>

        <div className="p-6 flex flex-col items-center justify-center flex-1 relative bg-[#EAEAEA]">
          <div className="absolute top-4 right-4 w-16 h-16 border-[4px] border-red-600 rounded-full text-red-600 flex items-center justify-center font-bold text-sm transform rotate-12 opacity-90 shadow-[2px_2px_0_#7f1d1d] z-10 bg-white/50 backdrop-blur-sm">回憶<br/>封裝</div>
          
          <div className="w-full text-left mb-2 border-b-2 border-gray-400 pb-2">
              <h3 className="text-gray-800 font-bold tracking-widest m-0 text-lg">民歌時光列車</h3>
              <p className="text-gray-500 text-[10px] tracking-widest m-0 font-bold">單程紀念車票</p>
          </div>
          
          {ticket ? (
            <img src={ticket.image} className="w-full rounded shadow-[2px_2px_0_#4b5563] border-2 border-gray-800 transform -rotate-2" alt="Ticket" />
          ) : (
            <div className="text-gray-500 border-2 border-dashed border-gray-400 w-full py-6 text-center rounded font-bold tracking-widest bg-white shadow-inner">無心情車票</div>
          )}
        </div>
      </div>

      <div className="flex-1 p-8 flex flex-col bg-[#FDFBF7] relative">
        
        <div className="border-b-[4px] border-gray-800 pb-2 mb-6 flex justify-between items-end">
          <h1 className="text-4xl font-bold font-serif text-gray-900 m-0 tracking-widest">{song.title}</h1>
          <span className="text-gray-600 font-serif tracking-wider font-bold">{song.singer}</span>
        </div>
        
        <div className="bg-red-50/80 border-l-[6px] border-red-600 p-5 italic text-gray-800 font-serif min-h-[90px] mb-6 text-lg leading-relaxed shadow-sm font-bold">
          「{customMessage || '這是一段專屬於民歌時代的美好回憶。'}」
        </div>

        <div className="flex-1 bg-[#EAEAEA] border-[3px] border-gray-800 p-6 pt-8 rounded-lg text-gray-800 font-serif overflow-hidden relative mb-2 shadow-inner">
          <div className="absolute top-0 left-0 w-full h-8 bg-gray-800 flex items-center justify-center text-xs text-white font-bold tracking-widest">
            — 記憶修復手稿 —
          </div>
          
          <div className="leading-loose tracking-widest whitespace-pre-wrap text-sm font-bold opacity-80 h-full overflow-hidden mt-2">
            {lyrics ? lyrics.content : '記憶尚未修復...'}
          </div>
          
          <div className="absolute bottom-0 left-0 w-full h-24 bg-gradient-to-t from-[#EAEAEA] via-[#EAEAEA]/90 to-transparent pointer-events-none"></div>
        </div>

        <div className="text-right text-xs text-gray-400 tracking-widest mt-2 font-bold uppercase">
          Generated by Folk Song Train Journey
        </div>
      </div>
    </div>
  );
};


const CapsuleGame = ({ song, ticket, cover, swapped, lyrics, recording, onHome }) => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [customMessage, setCustomMessage] = useState("");
  const [selectedCoverType, setSelectedCoverType] = useState('cover'); 

  const selectedCoverImg = selectedCoverType === 'swapped' && swapped ? swapped.image : (cover ? cover.image : null);

  const handleDownloadImage = async () => {
    setIsGenerating(true);
    
    try {
      const captureContainer = document.createElement('div');
      captureContainer.style.position = 'absolute';
      captureContainer.style.top = '-9999px';
      captureContainer.style.left = '-9999px';
      document.body.appendChild(captureContainer);

      const previewElement = document.getElementById('postcard-preview-content');
      captureContainer.innerHTML = previewElement.outerHTML;

      const canvas = await html2canvas(captureContainer.firstElementChild, {
        scale: 2, 
        useCORS: true, 
        backgroundColor: 'transparent'
      });
      
      const imageURL = canvas.toDataURL("image/png");
      const link = document.createElement('a');
      link.download = `${song.title}_民歌回憶明信片.png`;
      link.href = imageURL;
      link.click();

      document.body.removeChild(captureContainer);

    } catch (e) {
      alert("圖片生成失敗，請重試！");
      console.error(e);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownloadAudio = () => {
    if (!recording || !recording.audioUrl) return;
    const link = document.createElement('a');
    link.href = recording.audioUrl;
    link.download = `${song.title}_我的演唱錄音.webm`; 
    link.click();
  };

  return (
    <div className="relative w-full h-full flex items-center justify-center overflow-hidden bg-transparent p-8 pt-16">
      
      {/* 統一UI的左側工作台 */}
      <div className="w-full max-w-7xl h-[85vh] bg-[#EAEAEA] rounded-xl shadow-2xl border-4 border-[#C0B8A3] flex overflow-hidden">
         
         <div className="w-1/3 bg-[#FDFBF7] p-8 border-r-4 border-dashed border-gray-400 flex flex-col overflow-y-auto custom-scrollbar z-20 shadow-xl">
            <h2 className="text-3xl font-bold text-gray-800 mb-2 tracking-widest font-serif border-b-2 border-red-500 pb-2 inline-block w-max">回憶封裝桌</h2>
            <p className="text-gray-500 mb-8 text-sm leading-relaxed font-bold mt-2">選擇封面並寫下留言，我們將為您生成專屬的明信片與錄音檔。</p>

            <div className="mb-8">
               <h3 className="font-bold text-white mb-3 bg-gray-800 px-3 py-1.5 rounded-md w-max text-xs tracking-widest shadow-[2px_2px_0_#4b5563]">步驟一：選擇明信片封面</h3>
               <div className="flex gap-4">
                  <div 
                    onClick={() => setSelectedCoverType('cover')}
                    className={`flex-1 cursor-pointer rounded-lg overflow-hidden border-4 transition-all ${selectedCoverType === 'cover' ? 'border-red-600 shadow-[4px_4px_0_#7f1d1d] scale-105' : 'border-gray-300 opacity-60 hover:opacity-100'}`}
                  >
                    {cover ? <img src={cover.image} className="w-full aspect-[4/3] object-cover bg-gray-200" alt="AI Cover" /> : <div className="w-full aspect-[4/3] bg-gray-300 flex items-center justify-center text-xs font-bold tracking-widest">無 AI 封面</div>}
                    <div className="bg-gray-800 text-white text-center text-xs py-1.5 tracking-widest font-bold border-t-2 border-gray-600">意境風景</div>
                  </div>
                  <div 
                    onClick={() => setSelectedCoverType('swapped')}
                    className={`flex-1 cursor-pointer rounded-lg overflow-hidden border-4 transition-all ${selectedCoverType === 'swapped' ? 'border-red-600 shadow-[4px_4px_0_#7f1d1d] scale-105' : 'border-gray-300 opacity-60 hover:opacity-100'}`}
                  >
                    {swapped ? <img src={swapped.image} className="w-full aspect-[4/3] object-cover bg-gray-200" alt="FaceSwap Cover" /> : <div className="w-full aspect-[4/3] bg-gray-300 flex items-center justify-center text-xs font-bold tracking-widest">無合照</div>}
                    <div className="bg-gray-800 text-white text-center text-xs py-1.5 tracking-widest font-bold border-t-2 border-gray-600">歌手合照</div>
                  </div>
               </div>
            </div>

            <div className="mb-8 flex-1 flex flex-col">
               <h3 className="font-bold text-white mb-3 bg-gray-800 px-3 py-1.5 rounded-md w-max text-xs tracking-widest shadow-[2px_2px_0_#4b5563]">步驟二：寫下心情留言</h3>
               <textarea 
                 value={customMessage}
                 onChange={(e) => setCustomMessage(e.target.value)}
                 placeholder="寫下您聽完這首歌的感觸，或是想對老朋友說的話..."
                 className="flex-1 w-full bg-[#EAEAEA] border-2 border-gray-400 rounded-lg p-4 font-serif text-gray-800 font-bold resize-none focus:outline-none focus:border-red-500 shadow-inner leading-relaxed text-sm"
               ></textarea>
            </div>

            <div className="flex flex-col gap-4 mt-auto">
               <button 
                 onClick={handleDownloadImage}
                 disabled={isGenerating}
                 className={`w-full py-4 text-[#F5F5F5] text-lg rounded-lg font-bold border-2 transition-all duration-300 flex items-center justify-center gap-3 tracking-widest
                   ${isGenerating ? 'bg-gray-400 border-gray-500 cursor-wait' : 'bg-red-600 border-red-800 shadow-[4px_4px_0_#7f1d1d] hover:translate-y-[2px] hover:shadow-[2px_2px_0_#7f1d1d]'}
                 `}
               >
                 {isGenerating ? <><span className="animate-spin">📸</span> 正在產生圖片...</> : "📥 下載互動明信片 (.png)"}
               </button>

               {recording ? (
                 <button 
                   onClick={handleDownloadAudio}
                   className="w-full py-4 text-white text-lg rounded-lg font-bold border-2 border-black shadow-[4px_4px_0_#4b5563] transition-all duration-300 flex items-center justify-center gap-3 tracking-widest bg-gray-800 hover:translate-y-[2px] hover:shadow-[2px_2px_0_#4b5563]"
                 >
                   📼 下載我的演唱錄音
                 </button>
               ) : (
                 <div className="w-full py-4 bg-[#FDFBF7] text-gray-500 text-center rounded-lg font-bold text-sm tracking-widest border-2 border-gray-400 border-dashed">
                   📼 此次無錄音紀錄
                 </div>
               )}
            </div>
         </div>

         {/* 右側：即時預覽區 */}
         <div className="w-2/3 bg-[#C0B8A3] p-10 flex items-center justify-center relative overflow-hidden">
            <div className="absolute top-4 left-6 text-gray-600/40 font-bold tracking-widest text-2xl font-serif">LIVE PREVIEW</div>
            
            <div className="transform scale-75 xl:scale-90 hover:scale-[0.92] transition-transform duration-500 origin-center drop-shadow-[0_20px_40px_rgba(0,0,0,0.4)] rotate-1 hover:rotate-0">
               <div id="postcard-preview-content">
                  <PostcardTemplate 
                    song={song}
                    ticket={ticket}
                    selectedCoverImg={selectedCoverImg}
                    customMessage={customMessage}
                    lyrics={lyrics}
                  />
               </div>
            </div>
         </div>

      </div>
    </div>
  );
};

export default CapsuleGame;